# Generated by Django 5.1.6 on 2025-02-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_section', models.CharField(max_length=100, unique=True)),
                ('section_description', models.TextField()),
                ('punishments', models.TextField()),
            ],
        ),
    ]
